version: '3'
services:
    mongodb:
        image: mongo:4.2.12
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=fos-docker
            - MONGO_INITDB_ROOT_USERNAME=fos-root
            - MONGO_INITDB_ROOT_PASSWORD=fos-pass
        volumes:
            - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
            - ./docker-runtime/mongodb:/data/db
        expose:
            - "27017"

    neo4j:
        image: neo4j:4.2.1
        hostname: neo4j
        container_name: neo4j
        volumes:
            - ./docker-runtime/neo4j/data:/data
        environment:
            NEO4J_AUTH: neo4j/password
            NEO4JLABS_PLUGINS: '["apoc"]'

#   todo add proper depends_on via waitforit or similar
    svc:
        depends_on:
          - neo4j
          - mongodb
        image: openjdk:11-jdk
        hostname: svc
        container_name: svc
        volumes:
            - ./config:/root/config:ro
            - ./target:/root
            - ../fos-batch/target:/batch:ro
        working_dir: /root
        entrypoint: ["java", "-jar", "/root/fos-svc.jar"]
        environment:
            SPRING_PROFILES_ACTIVE: docker,production,batch
        ports:
            - "8099:8084"
       
    ui:
        depends_on:
          - svc
        image: nginx:1.19.8
        hostname: ui
        container_name: ui
        volumes:
            - ./fos-ui/build:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8100:80"
